name: 'setup-otel'
description: 'Set up your GitHub Actions workflow with a specific version of OpenTelemetry'
inputs:
  otel-version:
    description: 'Version to download'
    required: true
  otel-distribution:
    description: 'Distribution to download'
    required: false
    default: 'otelcol-contrib'
  architecture:
    description: "The target architecture (amd64, arm64) of the binary."
    required: false
    default: 'amd64'
outputs:
  otel-version:
    description: "The installed version."
  cache-hit:
    description: "A boolean value to indicate a cache entry was found"
  otel-path:
    description: "The absolute path to the otel executable."
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'activity'
  color: 'orange'
